### PR TITLE
Use standard logging format

### LINKED ISSUE #24: Use standard logging format
To put it bluntly, logging is a bit of a mess right now. Standardize logging everywhere and

- Use standard format for errors and warning that looks like this: `failed to do action: error message`.
- All debug and info level logs should be lowercase.
- Use zap logger features like structured logging.

Example:
```go
func OnMessageRemove(b *bot.Bot) func(*discordgo.Session, *discordgo.MessageDelete) {
	return func(s *discordgo.Session, m *discordgo.MessageDelete) {
		msg, ok := b.EmbedCache.Get(m.ChannelID, m.ID)
                if !ok {
                    return
                }

		log := b.Log.With(
		    "guild_id": m.GuildID,
                    "channel_id": m.ChannelID,
                    "message_id": m.ID,
                    "author_id": msg.AuthorID,
                )

                log.Debug("artwork message was removed, deleting embeds")
                
               // Bunch of other code
       }
}
```

It's okay to add more logs in scope of this issue, but it's not required.

### PR DESCRIPTION
**Pull request by Mihai22125**
Resolves #24

- Standardize logs from handlers package

### CODE REVIEW

**Comment by VTGare** [comment]
Other than that it looks good, thanks for adding extra context and fixing minor spelling mistakes. :)

File: handlers/handlers.go [hunk 1]
```diff
@@ -119,40 +119,44 @@ func RegisterHandlers(b *bot.Bot) {
 	b.AddHandler(OnMessageRemove(b))
 }
 
-//OnReady logs that bot's up.
+// OnReady logs that bot's up.
 func OnReady(b *bot.Bot) func(*discordgo.Session, *discordgo.Ready) {
 	return func(s *discordgo.Session, r *discordgo.Ready) {
-		b.Log.Infof("%v is online. Session ID: %v. Guilds: %v", r.User.String(), r.SessionID, len(r.Guilds))
+		b.Log.With("user", r.User.String(), "session_id", r.SessionID, "guilds", len(r.Guilds)).Info("user is online")
```
Comment (VTGare) [inline handlers/handlers.go:125]:
```suggestion
		b.Log.With("user", r.User.String(), "session_id", r.SessionID, "guilds", len(r.Guilds)).Info("shard is connected")
```

**Review by VTGare — APPROVED** [review]
